# Cell outputs

On this page you can see the results from each cell shown in Brent_Crude

# Brent Crude Oil Analysis

## 1. Get and clean the data

Collecting histdata
  Using cached histdata-1.1-py3-none-any.whl (9.2 kB)
Requirement already satisfied: pandas in /opt/conda/lib/python3.10/site-packages (1.4.2)
Requirement already satisfied: requests in /opt/conda/lib/python3.10/site-packages (from histdata) (2.27.1)
Requirement already satisfied: beautifulsoup4 in /opt/conda/lib/python3.10/site-packages (from histdata) (4.11.1)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.10/site-packages (from pandas) (2022.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /opt/conda/lib/python3.10/site-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.21.0 in /opt/conda/lib/python3.10/site-packages (from pandas) (1.22.3)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.10/site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Requirement already satisfied: soupsieve>1.2 in /opt/conda/lib/python3.10/site-packages (from beautifulsoup4->histdata) (2.3.1)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.10/site-packages (from requests->histdata) (2024.12.14)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/conda/lib/python3.10/site-packages (from requests->histdata) (1.26.9)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.10/site-packages (from requests->histdata) (3.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in /opt/conda/lib/python3.10/site-packages (from requests->histdata) (2.0.12)
Installing collected packages: histdata
Successfully installed histdata-1.1
WARNING: You are using pip version 22.0.4; however, version 26.2.1 is available.
You should consider upgrading via the '/opt/conda/bin/python -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

Downloading 2023
https://www.histdata.com/download-free-forex-historical-data/?/ascii/1-minute-bar-quotes/bcousd/2023
{'tk': 'f6c4d36f8fe7cac94fe4f5ae075bc3b6', 'date': '2023', 'datemonth': '2023', 'platform': 'ASCII', 'timeframe': 'M1', 'fxpair': 'BCOUSD'}
Wrote to brent_data/DAT_ASCII_BCOUSD_M1_2023.zip
brent_data/DAT_ASCII_BCOUSD_M1_2023.zip

Downloading BCO/USD M1 data for 2024...
https://www.histdata.com/download-free-forex-historical-data/?/ascii/1-minute-bar-quotes/bcousd/2024
{'tk': 'b4a2b7b06f2c5abc846668862625b81c', 'date': '2024', 'datemonth': '2024', 'platform': 'ASCII', 'timeframe': 'M1', 'fxpair': 'BCOUSD'}
Wrote to brent_data/DAT_ASCII_BCOUSD_M1_2024.zip
2024 completed.
brent_data/DAT_ASCII_BCOUSD_M1_2024.zip

Downloading BCO/USD M1 data for 2025...
https://www.histdata.com/download-free-forex-historical-data/?/ascii/1-minute-bar-quotes/bcousd/2025
{'tk': 'd3bedbf1f6bb5bd7619c5e29d18728b5', 'date': '2025', 'datemonth': '2025', 'platform': 'ASCII', 'timeframe': 'M1', 'fxpair': 'BCOUSD'}
Wrote to brent_data/DAT_ASCII_BCOUSD_M1_2025.zip
2025 completed.
brent_data/DAT_ASCII_BCOUSD_M1_2025.zip

Downloading BCO/USD M1 data for 2026-01...
https://www.histdata.com/download-free-forex-historical-data/?/ascii/1-minute-bar-quotes/bcousd/2026/1
{'tk': 'cb19b454a3dd8aa309a42a00c8cc12d4', 'date': '2026', 'datemonth': '202601', 'platform': 'ASCII', 'timeframe': 'M1', 'fxpair': 'BCOUSD'}
Wrote to brent_data/DAT_ASCII_BCOUSD_M1_202601.zip
2026-01 completed.
brent_data/DAT_ASCII_BCOUSD_M1_202601.zip

Downloading BCO/USD M1 data for 2026-02...
https://www.histdata.com/download-free-forex-historical-data/?/ascii/1-minute-bar-quotes/bcousd/2026/2
{'tk': '28b0179aee82498fb146ce3754f4b521', 'date': '2026', 'datemonth': '202602', 'platform': 'ASCII', 'timeframe': 'M1', 'fxpair': 'BCOUSD'}
Wrote to brent_data/DAT_ASCII_BCOUSD_M1_202602.zip
2026-02 completed.
brent_data/DAT_ASCII_BCOUSD_M1_202602.zip

Downloading BCO/USD M1 data for 2026-03...
https://www.histdata.com/download-free-forex-historical-data/?/ascii/1-minute-bar-quotes/bcousd/2026/3
{'tk': 'adc7779ea1b24ebb59e05498db8ae249', 'date': '2026', 'datemonth': '202603', 'platform': 'ASCII', 'timeframe': 'M1', 'fxpair': 'BCOUSD'}
Wrote to brent_data/DAT_ASCII_BCOUSD_M1_202603.zip
2026-03 completed.
brent_data/DAT_ASCII_BCOUSD_M1_202603.zip

Downloading BCO/USD M1 data for 2026-04...
https://www.histdata.com/download-free-forex-historical-data/?/ascii/1-minute-bar-quotes/bcousd/2026/4
{'tk': 'd1835777be25ae7b32328a02b9396f84', 'date': '2026', 'datemonth': '202604', 'platform': 'ASCII', 'timeframe': 'M1', 'fxpair': 'BCOUSD'}
Wrote to brent_data/DAT_ASCII_BCOUSD_M1_202604.zip
2026-04 completed.
brent_data/DAT_ASCII_BCOUSD_M1_202604.zip

Downloading BCO/USD M1 data for 2026-05...
https://www.histdata.com/download-free-forex-historical-data/?/ascii/1-minute-bar-quotes/bcousd/2026/5
{'tk': '187f542312c548180a7c99826591d551', 'date': '2026', 'datemonth': '202605', 'platform': 'ASCII', 'timeframe': 'M1', 'fxpair': 'BCOUSD'}
Wrote to brent_data/DAT_ASCII_BCOUSD_M1_202605.zip
2026-05 completed.
brent_data/DAT_ASCII_BCOUSD_M1_202605.zip

Downloading BCO/USD M1 data for 2026-06...
https://www.histdata.com/download-free-forex-historical-data/?/ascii/1-minute-bar-quotes/bcousd/2026/6
{'tk': '1f4c78dfe8e8ad0539b679c73a4e4253', 'date': '2026', 'datemonth': '202606', 'platform': 'ASCII', 'timeframe': 'M1', 'fxpair': 'BCOUSD'}
Wrote to brent_data/DAT_ASCII_BCOUSD_M1_202606.zip
2026-06 completed.
brent_data/DAT_ASCII_BCOUSD_M1_202606.zip

Downloading BCO/USD M1 data for 2026-07...
https://www.histdata.com/download-free-forex-historical-data/?/ascii/1-minute-bar-quotes/bcousd/2026/7
{'tk': 'c4b5c12ca50a4164629c7d5b84376b0a', 'date': '2026', 'datemonth': '202607', 'platform': 'ASCII', 'timeframe': 'M1', 'fxpair': 'BCOUSD'}
Wrote to brent_data/DAT_ASCII_BCOUSD_M1_202607.zip
2026-07 completed.
brent_data/DAT_ASCII_BCOUSD_M1_202607.zip

Downloading BCO/USD M1 data for 2026-08...
https://www.histdata.com/download-free-forex-historical-data/?/ascii/1-minute-bar-quotes/bcousd/2026/8
{'tk': '9da85724a9cf18e268e81b4a276ca50a', 'date': '2026', 'datemonth': '202608', 'platform': 'ASCII', 'timeframe': 'M1', 'fxpair': 'BCOUSD'}
Wrote to brent_data/DAT_ASCII_BCOUSD_M1_202608.zip
2026-08 completed.
brent_data/DAT_ASCII_BCOUSD_M1_202608.zip

ZIP files found: 11
Reading DAT_ASCII_BCOUSD_M1_2023.zip
Reading DAT_ASCII_BCOUSD_M1_2024.zip
Reading DAT_ASCII_BCOUSD_M1_2025.zip
Reading DAT_ASCII_BCOUSD_M1_202601.zip
Reading DAT_ASCII_BCOUSD_M1_202602.zip
Reading DAT_ASCII_BCOUSD_M1_202603.zip
Reading DAT_ASCII_BCOUSD_M1_202604.zip
Reading DAT_ASCII_BCOUSD_M1_202605.zip
Reading DAT_ASCII_BCOUSD_M1_202606.zip
Reading DAT_ASCII_BCOUSD_M1_202607.zip
Reading DAT_ASCII_BCOUSD_M1_202608.zip

Raw observations: 1,111,199

Final observations: 1,111,011
Missing timestamps: 0
Duplicate timestamps: 0
Chronologically sorted: True
First observation: 2023-01-02 20:00:00
Last observation: 2026-08-07 16:58:00

## 2. A quick look at the data

30 largest absolute minute price movements:

    Unnamed: 0            timestamp     open     high      low    close  log_return                     source_file
0        56640  2023-03-13 10:00:00   81.853   81.868   81.798   81.838    0.036332    DAT_ASCII_BCOUSD_M1_2023.zip
1        58671  2023-03-15 14:00:00   74.298   74.438   74.298   74.438    0.035901    DAT_ASCII_BCOUSD_M1_2023.zip
2        69823  2023-04-02 20:00:00   84.928   84.958   84.873   84.898    0.061676    DAT_ASCII_BCOUSD_M1_2023.zip
3       113924  2023-06-08 12:00:00   73.848   73.857   73.678   73.693   -0.037161    DAT_ASCII_BCOUSD_M1_2023.zip
4       209041  2023-10-08 20:00:00   87.358   87.393   87.313   87.328    0.034139    DAT_ASCII_BCOUSD_M1_2023.zip
5       543769  2024-10-27 19:00:00   72.932   72.987   72.922   72.932   -0.040350    DAT_ASCII_BCOUSD_M1_2024.zip
6       683031  2025-04-06 20:00:00   63.340   63.485   63.303   63.465   -0.038135    DAT_ASCII_BCOUSD_M1_2025.zip
7       706839  2025-05-04 20:00:00   59.000   59.000   58.900   58.965   -0.040498    DAT_ASCII_BCOUSD_M1_2025.zip
8       943225  2026-02-01 20:00:00   67.787   67.792   67.165   67.255   -0.036813  DAT_ASCII_BCOUSD_M1_202602.zip
9       968241  2026-03-01 20:00:00   78.312   78.375   78.175   78.220    0.067464  DAT_ASCII_BCOUSD_M1_202603.zip
10      974541  2026-03-08 19:00:00  108.173  108.212  107.977  108.007    0.149457  DAT_ASCII_BCOUSD_M1_202603.zip
11      975721  2026-03-09 14:40:00   84.553   88.567   84.553   88.527    0.045645  DAT_ASCII_BCOUSD_M1_202603.zip
12      975801  2026-03-09 19:00:00   93.008   93.083   91.447   91.452    0.031175  DAT_ASCII_BCOUSD_M1_202603.zip
13      978321  2026-03-11 19:00:00   96.557   97.432   96.207   97.422    0.046775  DAT_ASCII_BCOUSD_M1_202603.zip
14      987806  2026-03-23 06:05:00  112.957  112.987  108.168  108.178   -0.043300  DAT_ASCII_BCOUSD_M1_202603.zip
15      987807  2026-03-23 06:06:00  108.168  108.478  103.388  103.423   -0.044951  DAT_ASCII_BCOUSD_M1_202603.zip
16      987809  2026-03-23 06:08:00  101.763  101.858   96.168   96.298   -0.068960  DAT_ASCII_BCOUSD_M1_202603.zip
17      992159  2026-03-26 19:00:00  100.477  100.742  100.277  100.647   -0.058374  DAT_ASCII_BCOUSD_M1_202603.zip
18     1000977  2026-04-07 20:00:00   93.747   93.747   92.637   92.767   -0.127738  DAT_ASCII_BCOUSD_M1_202604.zip
19     1004757  2026-04-12 20:00:00  103.023  103.277  102.968  103.235    0.089605  DAT_ASCII_BCOUSD_M1_202604.zip
20     1011057  2026-04-19 20:00:00   96.642   96.850   96.598   96.645    0.049832  DAT_ASCII_BCOUSD_M1_202604.zip
21     1017335  2026-04-26 20:00:00  101.228  101.285  101.205  101.222   -0.047791  DAT_ASCII_BCOUSD_M1_202604.zip
22     1029933  2026-05-10 20:00:00  104.853  104.925  104.823  104.895    0.042275  DAT_ASCII_BCOUSD_M1_202605.zip
23     1042528  2026-05-24 20:00:00   98.658   98.845   98.635   98.635   -0.052166  DAT_ASCII_BCOUSD_M1_202605.zip
24     1044818  2026-05-26 20:00:00   96.407   96.417   96.287   96.365   -0.034193  DAT_ASCII_BCOUSD_M1_202605.zip
25     1061099  2026-06-14 20:00:00   83.760   83.860   83.755   83.850   -0.033909  DAT_ASCII_BCOUSD_M1_202606.zip
26     1085835  2026-07-12 20:00:00   78.437   78.480   78.390   78.420    0.031517  DAT_ASCII_BCOUSD_M1_202607.zip
27     1098433  2026-07-26 20:00:00   91.892   91.945   91.767   91.945   -0.067515  DAT_ASCII_BCOUSD_M1_202607.zip
28     1100934  2026-07-28 20:00:00   84.092   84.435   84.067   84.435    0.031925  DAT_ASCII_BCOUSD_M1_202607.zip
29     1104713  2026-08-02 20:00:00   83.852   83.985   83.827   83.945   -0.065272  DAT_ASCII_BCOUSD_M1_202608.zip

count    1.111010e+06
mean    -3.612642e-08
std      7.142982e-04
min     -1.277381e-01
0.1%    -4.285091e-03
1%      -1.720566e-03
5%      -8.493379e-04
50%      0.000000e+00
95%      8.526664e-04
99%      1.710860e-03
99.9%    3.957897e-03
max      1.494568e-01
Name: log_return, dtype: float64

## 3. Trump events and Brent prices

    Unnamed: 0  pre_window_minutes          removed_event  N_remaining  correct  accuracy    CI_low   CI_high   p_value
0            0                   5      IRAN_20260309_GOP            9        5  0.555556  0.266651  0.811221  1.000000
1            1                   5  IRAN_20260317_IRELAND            9        4  0.444444  0.188779  0.733349  1.000000
2            2                   5    IRAN_20260319_JAPAN            9        4  0.444444  0.188779  0.733349  1.000000
3            3                   5     IRAN_20260320_NAVY            9        5  0.555556  0.266651  0.811221  1.000000
4            4                   5  IRAN_20260323_MEMPHIS            9        4  0.444444  0.188779  0.733349  1.000000
5            5                   5  IRAN_20260327_FARMERS            9        4  0.444444  0.188779  0.733349  1.000000
6            6                   5    IRAN_20260327_MIAMI            9        5  0.555556  0.266651  0.811221  1.000000
7            7                   5     IRAN_20260331_OVAL            9        5  0.555556  0.266651  0.811221  1.000000
8            8                   5  IRAN_20260331_ADDRESS            9        5  0.555556  0.266651  0.811221  1.000000
9            9                   5   IRAN_20260406_EASTER            9        4  0.444444  0.188779  0.733349  1.000000
10          10                  15      IRAN_20260309_GOP           11        5  0.454545  0.212713  0.719908  1.000000
11          11                  15  IRAN_20260317_IRELAND           11        5  0.454545  0.212713  0.719908  1.000000
12          12                  15    IRAN_20260319_JAPAN           11        5  0.454545  0.212713  0.719908  1.000000
13          13                  15     IRAN_20260320_NAVY           11        4  0.363636  0.151665  0.646199  0.548828
14          14                  15  IRAN_20260323_MEMPHIS           11        4  0.363636  0.151665  0.646199  0.548828
15          15                  15     IRAN_20260325_NRCC           11        5  0.454545  0.212713  0.719908  1.000000
16          16                  15  IRAN_20260327_FARMERS           11        5  0.454545  0.212713  0.719908  1.000000
17          17                  15    IRAN_20260327_MIAMI           11        4  0.363636  0.151665  0.646199  0.548828
18          18                  15     IRAN_20260331_OVAL           11        5  0.454545  0.212713  0.719908  1.000000
19          19                  15  IRAN_20260331_ADDRESS           11        4  0.363636  0.151665  0.646199  0.548828
20          20                  15   IRAN_20260406_EASTER           11        5  0.454545  0.212713  0.719908  1.000000
21          21                  15    IRAN_20260406_PRESS           11        4  0.363636  0.151665  0.646199  0.548828
22          22                  30      IRAN_20260309_GOP           11        4  0.363636  0.151665  0.646199  0.548828
23          23                  30  IRAN_20260317_IRELAND           11        3  0.272727  0.097461  0.565645  0.226562
24          24                  30    IRAN_20260319_JAPAN           11        4  0.363636  0.151665  0.646199  0.548828
25          25                  30     IRAN_20260320_NAVY           11        4  0.363636  0.151665  0.646199  0.548828
26          26                  30  IRAN_20260323_MEMPHIS           11        4  0.363636  0.151665  0.646199  0.548828
27          27                  30     IRAN_20260325_NRCC           11        4  0.363636  0.151665  0.646199  0.548828
28          28                  30  IRAN_20260327_FARMERS           11        3  0.272727  0.097461  0.565645  0.226562
29          29                  30    IRAN_20260327_MIAMI           11        3  0.272727  0.097461  0.565645  0.226562
30          30                  30     IRAN_20260331_OVAL           11        4  0.363636  0.151665  0.646199  0.548828
31          31                  30  IRAN_20260331_ADDRESS           11        4  0.363636  0.151665  0.646199  0.548828
32          32                  30   IRAN_20260406_EASTER           11        4  0.363636  0.151665  0.646199  0.548828
33          33                  30    IRAN_20260406_PRESS           11        3  0.272727  0.097461  0.565645  0.226562
34          34                  60      IRAN_20260309_GOP           11        6  0.545455  0.280092  0.787287  1.000000
35          35                  60  IRAN_20260317_IRELAND           11        5  0.454545  0.212713  0.719908  1.000000
36          36                  60    IRAN_20260319_JAPAN           11        5  0.454545  0.212713  0.719908  1.000000
37          37                  60     IRAN_20260320_NAVY           11        6  0.545455  0.280092  0.787287  1.000000
38          38                  60  IRAN_20260323_MEMPHIS           11        6  0.545455  0.280092  0.787287  1.000000
39          39                  60     IRAN_20260325_NRCC           11        6  0.545455  0.280092  0.787287  1.000000
40          40                  60  IRAN_20260327_FARMERS           11        5  0.454545  0.212713  0.719908  1.000000
41          41                  60    IRAN_20260327_MIAMI           11        5  0.454545  0.212713  0.719908  1.000000
42          42                  60     IRAN_20260331_OVAL           11        6  0.545455  0.280092  0.787287  1.000000
43          43                  60  IRAN_20260331_ADDRESS           11        5  0.454545  0.212713  0.719908  1.000000
44          44                  60   IRAN_20260406_EASTER           11        6  0.545455  0.280092  0.787287  1.000000
45          45                  60    IRAN_20260406_PRESS           11        5  0.454545  0.212713  0.719908  1.000000
46          46                 120      IRAN_20260309_GOP           11        7  0.636364  0.353801  0.848335  0.548828
47          47                 120  IRAN_20260317_IRELAND           11        6  0.545455  0.280092  0.787287  1.000000
48          48                 120    IRAN_20260319_JAPAN           11        6  0.545455  0.280092  0.787287  1.000000
49          49                 120     IRAN_20260320_NAVY           11        6  0.545455  0.280092  0.787287  1.000000
50          50                 120  IRAN_20260323_MEMPHIS           11        7  0.636364  0.353801  0.848335  0.548828
51          51                 120     IRAN_20260325_NRCC           11        7  0.636364  0.353801  0.848335  0.548828
52          52                 120  IRAN_20260327_FARMERS           11        6  0.545455  0.280092  0.787287  1.000000
53          53                 120    IRAN_20260327_MIAMI           11        6  0.545455  0.280092  0.787287  1.000000
54          54                 120     IRAN_20260331_OVAL           11        7  0.636364  0.353801  0.848335  0.548828
55          55                 120  IRAN_20260331_ADDRESS           11        7  0.636364  0.353801  0.848335  0.548828
56          56                 120   IRAN_20260406_EASTER           11        6  0.545455  0.280092  0.787287  1.000000
57          57                 120    IRAN_20260406_PRESS           11        6  0.545455  0.280092  0.787287  1.000000

### Testing whether the pre-event movement was related to the post-event movement

    Unnamed: 0  pre_minutes  post_minutes   N  pearson_r   p_value  spearman_rho  spearman_p  directional_accuracy  directional_p  bonferroni_p
0            0          120            15  14  -0.608618  0.020903     -0.198020    0.497383              0.428571       0.790527      0.522571
1            1          120            60  14  -0.567358  0.034341     -0.277228    0.337271              0.428571       0.790527      0.858514
2            2          120            30  14  -0.539804  0.046323     -0.303631    0.291271              0.285714       0.179565      1.000000
3            3           60            60  14  -0.409921  0.145482     -0.387239    0.171338              0.428571       0.790527      1.000000
4            4           60            15  14  -0.391300  0.166504     -0.532454    0.049979              0.428571       0.790527      1.000000
5            5           60            30  14  -0.387463  0.171069     -0.484049    0.079456              0.285714       0.179565      1.000000
6            6          120           120  14  -0.327261  0.253396     -0.140814    0.631114              0.500000       1.000000      1.000000
7            7           30            60  14  -0.315197  0.272341     -0.655666    0.010901              0.285714       0.179565      1.000000
8            8           15           120  14  -0.296999  0.302463     -0.677668    0.007742              0.285714       0.179565      1.000000
9            9           60           120  14  -0.292928  0.309453     -0.479648    0.082635              0.500000       1.000000      1.000000
10          10           30           120  14  -0.276887  0.337890     -0.708471    0.004567              0.357143       0.423950      1.000000
11          11           30            30  14  -0.275927  0.339636     -0.607261    0.021269              0.285714       0.179565      1.000000
12          12           30            15  14  -0.267176  0.355788     -0.514852    0.059579              0.428571       0.790527      1.000000
13          13           60             5  14  -0.261044  0.367350     -0.593825    0.025156              0.214286       0.057373      1.000000
14          14           15            60  14  -0.240947  0.406641     -0.264027    0.361702              0.357143       0.423950      1.000000
15          15            5           120  14  -0.239069  0.410420     -0.391639    0.166104              0.142857       0.012939      1.000000
16          16            5            60  14  -0.230898  0.427070     -0.004400    0.988088              0.357143       0.423950      1.000000
17          17          120             5  14  -0.230137  0.428639     -0.200885    0.491052              0.214286       0.057373      1.000000
18          18           15            15  14  -0.219113  0.451673     -0.281628    0.329337              0.357143       0.423950      1.000000
19          19           30             5  14  -0.215500  0.459354     -0.514354    0.059868              0.214286       0.057373      1.000000
20          20            5            15  14  -0.189040  0.517468     -0.079208    0.787807              0.285714       0.179565      1.000000
21          21            5            30  14  -0.182269  0.532849     -0.193619    0.507180              0.285714       0.179565      1.000000
22          22           15            30  14  -0.181342  0.534969     -0.294830    0.306176              0.357143       0.423950      1.000000
23          23            5             5  14  -0.063181  0.830101     -0.028698    0.922421              0.357143       0.423950      1.000000
24          24           15             5  14  -0.037709  0.898163     -0.108169    0.712814              0.428571       0.790527      1.000000

### A simple robustness check

    pre_window_minutes  removed_row  accuracy   p_value
0                    5            0  0.555556  1.000000
1                    5            1  0.444444  1.000000
2                    5            2  0.444444  1.000000
3                    5            3  0.555556  1.000000
4                    5            4  0.444444  1.000000
5                    5            5  0.444444  1.000000
6                    5            6  0.555556  1.000000
7                    5            7  0.555556  1.000000
8                    5            8  0.555556  1.000000
9                    5            9  0.444444  1.000000
10                  15            0  0.454545  1.000000
11                  15            1  0.454545  1.000000
12                  15            2  0.454545  1.000000
13                  15            3  0.363636  0.548828
14                  15            4  0.363636  0.548828
15                  15            5  0.454545  1.000000
16                  15            6  0.454545  1.000000
17                  15            7  0.363636  0.548828
18                  15            8  0.454545  1.000000
19                  15            9  0.363636  0.548828
20                  15           10  0.454545  1.000000
21                  15           11  0.363636  0.548828
22                  30            0  0.363636  0.548828
23                  30            1  0.272727  0.226562
24                  30            2  0.363636  0.548828
25                  30            3  0.363636  0.548828
26                  30            4  0.363636  0.548828
27                  30            5  0.363636  0.548828
28                  30            6  0.272727  0.226562
29                  30            7  0.272727  0.226562
30                  30            8  0.363636  0.548828
31                  30            9  0.363636  0.548828
32                  30           10  0.363636  0.548828
33                  30           11  0.272727  0.226562
34                  60            0  0.545455  1.000000
35                  60            1  0.454545  1.000000
36                  60            2  0.454545  1.000000
37                  60            3  0.545455  1.000000
38                  60            4  0.545455  1.000000
39                  60            5  0.545455  1.000000
40                  60            6  0.454545  1.000000
41                  60            7  0.454545  1.000000
42                  60            8  0.545455  1.000000
43                  60            9  0.454545  1.000000
44                  60           10  0.545455  1.000000
45                  60           11  0.454545  1.000000
46                 120            0  0.636364  0.548828
47                 120            1  0.545455  1.000000
48                 120            2  0.545455  1.000000
49                 120            3  0.545455  1.000000
50                 120            4  0.636364  0.548828
51                 120            5  0.636364  0.548828
52                 120            6  0.545455  1.000000
53                 120            7  0.545455  1.000000
54                 120            8  0.636364  0.548828
55                 120            9  0.636364  0.548828
56                 120           10  0.545455  1.000000
57                 120           11  0.545455  1.000000

## 4. Holding Brent over the weekend during the Iran conflict

Complete weekends: 21

   week_start_date  week_start             week_end  monday_open  friday_close  intraday_volatility  realised_volatility  weekend_return_long  weekend_return_short  hold_advantage_long  hold_advantage_short
0       2026-03-02  2026-03-02  2026-03-06 16:59:00       77.570        93.013             0.001402             0.844572             0.253878             -0.253878             0.254878             -0.252878
1       2026-03-09  2026-03-09  2026-03-13 15:59:00      116.627       103.797             0.003928             2.366330             0.009230             -0.009230             0.010230             -0.008230
2       2026-03-16  2026-03-16  2026-03-20 15:59:00      104.755       112.490             0.001341             0.807617             0.001822             -0.001822             0.002822             -0.000822
3       2026-03-23  2026-03-23  2026-03-27 15:59:00      112.695       106.817             0.002082             1.254207             0.009184             -0.009184             0.010184             -0.008184
4       2026-04-06  2026-04-06  2026-04-10 16:59:00      109.815        94.387             0.002092             1.259922             0.081982             -0.081982             0.082982             -0.080982
5       2026-04-13  2026-04-13  2026-04-17 16:59:00      102.125        91.947             0.001473             0.887164             0.035705             -0.035705             0.036705             -0.034705
6       2026-04-20  2026-04-20  2026-04-24 16:40:00       95.230       106.177             0.001274             0.767494            -0.055021              0.055021            -0.054021              0.056021
7       2026-04-27  2026-04-27  2026-05-01 16:59:00      100.335       108.777             0.001218             0.733441            -0.003401              0.003401            -0.002401              0.004401
8       2026-05-04  2026-05-04  2026-05-08 16:59:00      108.407       100.553             0.001375             0.828295             0.050640             -0.050640             0.051640             -0.049640
9       2026-05-11  2026-05-11  2026-05-15 16:59:00      105.645       109.167             0.000946             0.569685             0.018440             -0.018440             0.019440             -0.017440
10      2026-05-18  2026-05-18  2026-05-22 16:59:00      111.180       103.917             0.001134             0.683114            -0.059682              0.059682            -0.058682              0.060682
11      2026-05-25  2026-05-25  2026-05-29 16:59:00       97.715        91.587             0.001279             0.770417             0.018343             -0.018343             0.019343             -0.017343
12      2026-06-01  2026-06-01  2026-06-05 16:59:00       93.267        92.847             0.000796             0.479583             0.037890             -0.037890             0.038890             -0.036890
13      2026-06-08  2026-06-08  2026-06-12 16:59:00       96.365        86.742             0.001096             0.660486            -0.040177              0.040177            -0.039177              0.041177
14      2026-06-15  2026-06-15  2026-06-19 13:28:00       83.257        80.340             0.000990             0.596141            -0.012509              0.012509            -0.011509              0.013509
15      2026-06-22  2026-06-22  2026-06-26 16:59:00       79.335        73.462             0.000755             0.454870            -0.002682              0.002682            -0.001682              0.003682
16      2026-06-29  2026-06-29  2026-07-03 13:28:00       73.265        71.925             0.000563             0.339053            -0.003198              0.003198            -0.002198              0.004198
17      2026-07-06  2026-07-06  2026-07-10 16:59:00       71.695        75.987             0.000784             0.472308             0.040507             -0.040507             0.041507             -0.039507
18      2026-07-13  2026-07-13  2026-07-17 16:59:00       79.065        88.072             0.001012             0.609758             0.024616             -0.024616             0.025616             -0.023616
19      2026-07-20  2026-07-20  2026-07-24 16:59:00       90.240        98.367             0.000960             0.578431            -0.057814              0.057814            -0.056814              0.058814
20      2026-07-27  2026-07-27  2026-07-31 16:58:00       92.680        89.607             0.001350             0.813119            -0.069325              0.069325            -0.068325              0.070325

### Does weekday volatility give any clue about the weekend result?

   Unnamed: 0       direction   n  pearson_r  pearson_p  spearman_rho  spearman_p  r_squared  regression_p  hold_wins  close_wins  hold_win_rate
0           0   LONG POSITION  21   0.119083   0.607164      0.235065     0.30503   0.014181      0.607164         12           9       0.571429
1           1  SHORT POSITION  21  -0.119083   0.607164     -0.235065     0.30503   0.014181      0.607164          9          12       0.428571

Long leave-one-week-out accuracy: 57.1%, p = 0.6636
Short leave-one-week-out accuracy: 57.1%, p = 0.6636

## 5. What I learned